name: learn-github-actions
on: [push]
jobs:
  composer-install:
    runs-on: ubuntu-latest
    steps:
      - name: Activate checkout@v2
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          tools: composer:v2
          php-version: '8.0'

      - name: Install dependencies
        run: composer install

      - name: Run units test
        run: ./vendor/bin/phpunit -c phpunit.xml