name: unit-tests-action
on: [push]
jobs:
  execute-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Activate checkout@v2
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: composer:v2

      - name: Install dependencies
        run: composer install

      - name: Run units test
        run: ./vendor/bin/phpunit -c phpunit.xml